global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'infobip-sms-api'
    static_configs:
      - targets: ['host.docker.internal:3001']
    scrape_interval: 5s
    metrics_path: '/metrics'